### ISSUE TITLE
Only use activeTab permission

### ISSUE THREAD

**Issue by fregante** [ngti/svg-grabber#4]
<blockquote>

The [activeTab](https://developer.chrome.com/extensions/activeTab) permission gives an extension temporary access to the currently active tab when the user invokes the extension - for example by clicking its browser action. Access to the tab lasts until the tab is navigated or closed.

This serves as an alternative for many uses of <all_urls>, but displays no warning message during installation:

Without activeTab |  With activeTab
-- | --
![](https://developer.chrome.com/static/images/active-tab-before.png) | ![](https://developer.chrome.com/static/images/active-tab-after.png)

</blockquote>

**Comment by riosjuan** [comment]
Good suggestion! I did some research and in order make full use of the activeTab permission it requires some refactoring to remove the content_scripts.
