### ISSUE TITLE
Extension doesn't work on sites with A LOT of SVGs

### ISSUE THREAD

**Issue by dziku86** [ngti/svg-grabber#9]
I was trying to download icons from [microsoft/fluentui-system-icons](https://github.com/microsoft/fluentui-system-icons/blob/master/icons.md) and svg-grabber do nothing on this site. It works everywhere else. I've installed the extension from Chrome Web Store.

Chrome 87.0.4280.88 (Official Build) (32-bit) (cohort: Stable)
OS Windows 7 Service Pack 1 (Build 7601)

**Comment by jardicc** [comment]
The number of requests that are running at the same time should be limited. I had a similar problem with my software.
